### ISSUE TITLE
Environment variable for default settings variant

### ISSUE THREAD

**Issue by iLLiCiTiT** [ynput/ayon-python-api#106]
## Description
We need to have option to define default settings variant via environment variables.

### Additional information
The environment variable should not be mandatory and if is not set then use `production` by default. Suggested name is `AYON_SETTINGS_VARIANT`.

**Comment by BigRoy** [comment]
Is this still relevant @iLLiCiTiT ? If so, when would you change "settings variants"? Isn't this just what staging versus dev versus production bundles do?

**Comment by iLLiCiTiT** [comment]
> Isn't this just what staging versus dev versus production bundles do?

No, bundles are bundles. Each bundle can have production, staging, and dev bundle can have settings. Like said many times, bundle is a definition of AYON launcher, addons and dependency package, in other words bundle != variant.

Anyway, resolved with https://github.com/ynput/ayon-python-api/pull/109
