### ISSUE TITLE
Add support to filter queries by nested fields

### ISSUE THREAD

**Issue by fabiaserra** [ynput/ayon-python-api#137]
Doing any queries in the API that filter by a field that contains nested attributes result in the following error:
```
> ayon_api.get_project(project_name, fields=["code", "taskTypes"])?
ayon_api.exceptions.GraphQlQueryFAILED: GraphQl query FAILED: Field 'taskTypes' of type '[ TaskType! ]!' must have a selection of subfields. Did you mean 'taskTypes { ... }'? (Line 4 Column 5)
```
This is a core functionality that should be easy to use to speed up queries. However, if you are going to implement it by querying everything and then filtering out don't even bother, the point should be to make queries faster or improve I/O because of using less memory, and if that's not the case, just document in the API that there's no point in specifying `fields` on the args, I would even argue that `fields` shouldn't even be exposed in that case.

**Comment by BigRoy** [comment]
> Doing any queries in the API that filter by a field that contains nested attributes result in the following error:

I know that nested queries is currently support for `attrib` access, like e.g. a folder entity query with `get_folders(..., fields={"attrib.frameStart"})`

That nested filtering format (by dot) matches how it was in OpenPype in `pymongo`. I'm not sure if that works for all keys - but just wanted to state there is some nested filtering in the codebase currently.
