### ISSUE TITLE
TypeError in `entity_hub.ProjectEntity.from_entity_data()`

### ISSUE THREAD

**Issue by dee-ynput** [ynput/ayon-python-api#159]
when using:
`ayon_api.entity_hub.ProjectEntity.from_entity_data()`

It raises:
`TypeError: ProjectEntity.__init__() missing 1 required positional argument: 'statuses'`
(The `ayon_api.entity_hub.ProjectEntity()` constructor indeed requires the statuses.)

I can use `ayon_api.entity_hub.EntityHub(project_name=name).project_entity` but since I already have the entity data I would like to avoid fetching them again.

**Comment by iLLiCiTiT** [comment]
Resolved with https://github.com/ynput/ayon-python-api/pull/160
