### ISSUE TITLE
Generated HTML api docs through sphinx and upload them as Github pages

### ISSUE THREAD

**Issue by mkolar** [ynput/ayon-python-api#21]
We should add infrastructure for sphinx documentation generation so we keep on top of it from the get go.

**Comment by mkolar** [comment]
The start of the work is already there in the api repo, however, we really should give it a little bit of love and the the api docs embedded on ayon.ynput.io/python_api or similar place (yes that url doesn't exist). That would effectively need some cleanup of the rst structure probably, a bit of CI in the repo and some research into embedding sphinx generated pages in docusaurus.

**Comment by tweak-wtf** [comment]
i recently built docs for LabLib using GH Actions hosting them on GH Pages. i used `sphinx` and the `furo` theme. 
just wanted to note in case it's of help for anyone.

built docs: https://ynput.github.io/LabLib/
workflow: https://github.com/ynput/LabLib/actions/runs/10013629681/workflow
